In [16]:
import pandas as pd
import numpy as np

# CSV 파일 불러오기
df = pd.read_csv('./전처리/개별재무제표/코스닥_베네시.csv')

# NaN 값과 무한대 값 처리
#df.replace([np.inf, -np.inf], np.nan, inplace=True)  # 무한대 값을 NaN으로 변환
#df.fillna(0, inplace=True)  # 모든 NaN 값을 0으로 대체

# 쉼표 제거 및 실수형 변환
columns_to_convert = ['매출액(천원)', '매출채권(천원)', '매출원가(천원)', '유동자산(천원)', '재고자산(천원)',
                      '유형자산(천원)', '총자산(천원)', '판매비와관리비(천원)', '당기순이익(천원)', '유동부채(천원)',
                      '비유동부채(천원)', '영업활동으로인한현금흐름(천원)', '영업이익(천원)', '유무형자산상각비(천원)']
for column in columns_to_convert:
    df[column] = df[column].astype(str).str.replace(',', '').astype(float)

# 데이터 확인
print(df.head())

    Symbol    Name  결산월   회계년      주기  매출채권(천원)  매출액(천원)  매출원가(천원)  유동자산(천원)  \
0  A247540  에코프로비엠   12  2011  Annual       NaN      NaN       NaN       NaN
1  A247540  에코프로비엠   12  2012  Annual       NaN      NaN       NaN       NaN
2  A247540  에코프로비엠   12  2013  Annual       NaN      NaN       NaN       NaN
3  A247540  에코프로비엠   12  2014  Annual       NaN      NaN       NaN       NaN
4  A247540  에코프로비엠   12  2015  Annual       NaN      NaN       NaN       NaN

   유형자산(천원)  총자산(천원)  재고자산(천원)  당기순이익(천원)  판매비와관리비(천원)  유동부채(천원)  비유동부채(천원)  \
0       NaN      NaN       NaN        NaN          NaN       NaN        NaN
1       NaN      NaN       NaN        NaN          NaN       NaN        NaN
2       NaN      NaN       NaN        NaN          NaN       NaN        NaN
3       NaN      NaN       NaN        NaN          NaN       NaN        NaN
4       NaN      NaN       NaN        NaN          NaN       NaN        NaN

   영업활동으로인한현금흐름(천원)  영업이익(천원)  유무형자산상각비(천원)
0               NaN       NaN           NaN
1               NaN       NaN           NaN
2               NaN       NaN           NaN
3               NaN       NaN           NaN
4               NaN       NaN           NaN

In [26]:
df.columns

Index(['Symbol', 'Name', '결산월', '회계년', '주기', '매출액(천원)', '매출채권(천원)', '매출원가(천원)',
       '유동자산(천원)', '재고자산(천원)', '유형자산(천원)', '총자산(천원)', '판매비와관리비(천원)',
       '당기순이익(천원)', '유동부채(천원)', '비유동부채(천원)', '영업활동으로인한현금흐름(천원)', '영업이익(천원)',
       '유무형자산상각비(천원)', 'DSRI', 'GMI', 'AQI', 'SGI', 'DEPI', 'SGAI', 'LVGI',
       'TATA'],
      dtype='object')

In [2]:
df.loc[df['Name'] =='주성코퍼레이션' ]

,Symbol,Name,결산월,회계년,주기,매출채권(천원),매출액(천원),매출원가(천원),유동자산(천원),유형자산(천원),총자산(천원),재고자산(천원),당기순이익(천원),판매비와관리비(천원),유동부채(천원),비유동부채(천원),영업활동으로인한현금흐름(천원),영업이익(천원),유무형자산상각비(천원)
5244,A109070,주성코퍼레이션,12,2011,Annual,29759424.0,119580484.0,120040602.0,85135815.0,52034728.0,146573043.0,29996226.0,-15318025.0,5289856.0,89643606.0,31187070.0,6591007.0,-5749974.0,3309775.0
5245,A109070,주성코퍼레이션,12,2012,Annual,25253242.0,91020427.0,91894698.0,61476190.0,44032000.0,105726256.0,19899951.0,-10571041.0,3448340.0,67230632.0,24003734.0,3790639.0,-4322610.0,2706429.0
5246,A109070,주성코퍼레이션,12,2013,Annual,15138708.0,56437351.0,55856626.0,32116990.0,41623550.0,74487642.0,14175025.0,-9049220.0,1906311.0,32791105.0,36139246.0,-1487360.0,-1325586.0,2399709.0
5247,A109070,주성코퍼레이션,12,2014,Annual,11008066.0,50354166.0,49646764.0,27396715.0,39345574.0,67495668.0,14055483.0,-4828402.0,2418614.0,47389230.0,14645514.0,-569040.0,-1711211.0,2289476.0
5248,A109070,주성코퍼레이션,12,2015,Annual,10785764.0,48044075.0,48748380.0,27088649.0,37786055.0,68293126.0,12774811.0,-5642910.0,2114706.0,15103469.0,41045828.0,744290.0,-2819011.0,2259683.0
5249,A109070,주성코퍼레이션,12,2016,Annual,9494988.0,45974763.0,49584839.0,29043978.0,12722528.0,50219241.0,9686323.0,-17554874.0,5276022.0,23598078.0,14887756.0,-3945628.0,-8886097.0,2291253.0
5250,A109070,주성코퍼레이션,12,2017,Annual,15784854.0,63031654.0,65765657.0,33775124.0,9347522.0,56315615.0,13467037.0,-6432127.0,6279611.0,41946536.0,3832738.0,-785842.0,-9013613.0,1672404.0
5251,A109070,주성코퍼레이션,12,2018,Annual,14948774.0,73829905.0,77609519.0,31633827.0,2742242.0,53533102.0,12157267.0,-19162283.0,7076650.0,47691961.0,3203041.0,-10422850.0,-10856264.0,1830904.0
5252,A109070,주성코퍼레이션,12,2019,Annual,3410766.0,43613941.0,43276574.0,14408883.0,1420662.0,26048049.0,3504771.0,-18237898.0,6368470.0,28306067.0,921073.0,-5222499.0,-6031103.0,771168.0
5253,A109070,주성코퍼레이션,12,2020,Annual,3840543.0,16807417.0,16131677.0,10671047.0,996322.0,19234975.0,2771185.0,-6675274.0,5563567.0,10918629.0,874098.0,-3451192.0,-4887827.0,578844.0
5254,A109070,주성코퍼레이션,12,2021,Annual,5053383.0,31858226.0,28290545.0,20520172.0,5349616.0,31654289.0,5626829.0,-2023482.0,6185229.0,15633644.0,5502555.0,-982366.0,-2617547.0,934331.0
5255,A109070,주성코퍼레이션,12,2022,Annual,4766120.0,20268668.0,19677189.0,24385796.0,4824989.0,31515779.0,4010315.0,-10557697.0,5666800.0,12105486.0,4313352.0,-4813402.0,-5075322.0,1008306.0

In [17]:
# 회사명으로 데이터 그룹화하여 DSRI 계산
for company in df['Name'].unique():
    company_data = df[df['Name'] == company]
    company_data['DSRI'] = (company_data['매출채권(천원)'] / company_data['매출액(천원)']) / (company_data['매출채권(천원)'].shift(1) / company_data['매출액(천원)'].shift(1))
    df.loc[company_data.index, 'DSRI'] = company_data['DSRI']

C:\Users\Master\AppData\Local\Temp\ipykernel_17828\1418162248.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['DSRI'] = (company_data['매출채권(천원)'] / company_data['매출액(천원)']) / (company_data['매출채권(천원)'].shift(1) / company_data['매출액(천원)'].shift(1))
C:\Users\Master\AppData\Local\Temp\ipykernel_17828\1418162248.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['DSRI'] = (company_data['매출채권(천원)'] / company_data['매출액(천원)']) / (company_data['매출채권(천원)'].shift(1) / company_data['매출액(천원)'].shift(1))

In [18]:
# t-1년도와 t년도의 값을 비교하여 새로운 열을 만들거나 해당 열을 변경
# # {(전기 매출액 - 전기 매출원가) / 전기 매출액} / {(당기 매출액 - 당기 매출원가) / 당기 매출액}
# GMI
for company in df['Name'].unique():
    company_data = df[df['Name'] == company]
    company_data['GMI'] = ((company_data['매출액(천원)'].shift(1) - company_data['매출원가(천원)'].shift(1)) / company_data['매출액(천원)'].shift(1)) / ((company_data['매출액(천원)'] - company_data['매출원가(천원)']) / company_data['매출액(천원)'])
    df.loc[company_data.index, 'GMI'] = company_data['GMI']

C:\Users\Master\AppData\Local\Temp\ipykernel_17828\1245762707.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['GMI'] = ((company_data['매출액(천원)'].shift(1) - company_data['매출원가(천원)'].shift(1)) / company_data['매출액(천원)'].shift(1)) / ((company_data['매출액(천원)'] - company_data['매출원가(천원)']) / company_data['매출액(천원)'])
C:\Users\Master\AppData\Local\Temp\ipykernel_17828\1245762707.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['GMI'] = ((company_data['매출액(천원)'].shift(1) - company_data['매출원가(천원)'].shift(1)) / company_data['매출액(천원)'].shift(1)) / ((company_data['매출액(천원)'] - company_data['매출원가(천원)']) / company_data['매출액(천원)'])

In [19]:
# t년도와 t-1년도의 값을 비교하여 새로운 열을 만들거나 해당 열을 변경
# ((1 - 당기유동자산 + 당기유형자산) / 당기총자산) / ((1 - 전기유동자산 + 전기 유형자산) / 전기총자산)
# AQI
for company in df['Name'].unique():
    company_data = df[df['Name'] == company]
    company_data['AQI'] = (1 - (company_data['유동자산(천원)'] + company_data['유형자산(천원)']) / company_data['총자산(천원)'])  / (1 - (company_data['유동자산(천원)'].shift(1) + company_data['유형자산(천원)'].shift(1)) / company_data['총자산(천원)'].shift(1))
    df.loc[company_data.index, 'AQI'] = company_data['AQI']

C:\Users\Master\AppData\Local\Temp\ipykernel_17828\666085873.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['AQI'] = (1 - (company_data['유동자산(천원)'] + company_data['유형자산(천원)']) / company_data['총자산(천원)'])  / (1 - (company_data['유동자산(천원)'].shift(1) + company_data['유형자산(천원)'].shift(1)) / company_data['총자산(천원)'].shift(1))
C:\Users\Master\AppData\Local\Temp\ipykernel_17828\666085873.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['AQI'] = (1 - (company_data['유동자산(천원)'] + company_data['유형자산(천원)']) / company_data['총자산(천원)'])  / (1 - (company_data['유동자산(천원)'].shift(1) + company_data['유형자산(천원)'].shift(1)) / company_data['총자산(천원)'].shift(1))

In [20]:
# t년도와 t-1년도의 값을 비교하여 새로운 열을 만들거나 해당 열을 변경
# 당기매출액 / 전기매출액
# SGI
for company in df['Name'].unique():
    company_data = df[df['Name'] == company]
    company_data['SGI'] = (company_data['매출액(천원)'] / company_data['매출액(천원)'].shift(1))
    df.loc[company_data.index, 'SGI'] = company_data['SGI']

C:\Users\Master\AppData\Local\Temp\ipykernel_17828\3506113922.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['SGI'] = (company_data['매출액(천원)'] / company_data['매출액(천원)'].shift(1))
C:\Users\Master\AppData\Local\Temp\ipykernel_17828\3506113922.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['SGI'] = (company_data['매출액(천원)'] / company_data['매출액(천원)'].shift(1))

In [21]:
# t-1년도와 t년도의 값을 비교하여 새로운 열을 만들거나 해당 열을 변경
# # (전기 감가상각비 / (전기 감가상각비 + 전기유형자산)) / (당기 감가상각비 / (당기 감가상각비 + 당기유형자산))
# DEPI
for company in df['Name'].unique():
    company_data = df[df['Name'] == company]
    company_data['DEPI'] = (company_data['유무형자산상각비(천원)'].shift(1) / (company_data['유무형자산상각비(천원)'].shift(1) + company_data['유형자산(천원)'].shift(1)))
    df.loc[company_data.index, 'DEPI'] = company_data['DEPI']

C:\Users\Master\AppData\Local\Temp\ipykernel_17828\1294813100.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['DEPI'] = (company_data['유무형자산상각비(천원)'].shift(1) / (company_data['유무형자산상각비(천원)'].shift(1) + company_data['유형자산(천원)'].shift(1)))
C:\Users\Master\AppData\Local\Temp\ipykernel_17828\1294813100.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['DEPI'] = (company_data['유무형자산상각비(천원)'].shift(1) / (company_data['유무형자산상각비(천원)'].shift(1) + company_data['유형자산(천원)'].shift(1)))

In [22]:
# t년도와 t-1년도의 값을 비교하여 새로운 열을 만들거나 해당 열을 변경
# (당기 판관비 / 당기 매출액) / (전기 판관비 / 전기 매출액)
# SGAI
for company in df['Name'].unique():
    company_data = df[df['Name'] == company]
    company_data['SGAI'] = (company_data['판매비와관리비(천원)'] / company_data['매출액(천원)']) / (company_data['판매비와관리비(천원)'].shift(1) / company_data['매출액(천원)'].shift(1))
    df.loc[company_data.index, 'SGAI'] = company_data['SGAI']

C:\Users\Master\AppData\Local\Temp\ipykernel_17828\41645748.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['SGAI'] = (company_data['판매비와관리비(천원)'] / company_data['매출액(천원)']) / (company_data['판매비와관리비(천원)'].shift(1) / company_data['매출액(천원)'].shift(1))
C:\Users\Master\AppData\Local\Temp\ipykernel_17828\41645748.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['SGAI'] = (company_data['판매비와관리비(천원)'] / company_data['매출액(천원)']) / (company_data['판매비와관리비(천원)'].shift(1) / company_data['매출액(천원)'].shift(1))

In [23]:
# t년도와 t-1년도의 값을 비교하여 새로운 열을 만들거나 해당 열을 변경
# ((당기 LTD + 당기 유동부채) / 당기 총자산) / ((전기 LTD + 전기 유동부채) / 전기 총자산)
# LVGI
for company in df['Name'].unique():
    company_data = df[df['Name'] == company]
    company_data['LVGI'] = ((company_data['비유동부채(천원)'] + company_data['유동부채(천원)']) / company_data['총자산(천원)']) / ((company_data['비유동부채(천원)'].shift(1) + company_data['유동부채(천원)'].shift(1)) / company_data['총자산(천원)'].shift(1))
    df.loc[company_data.index, 'LVGI'] = company_data['LVGI']

C:\Users\Master\AppData\Local\Temp\ipykernel_17828\278330576.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['LVGI'] = ((company_data['비유동부채(천원)'] + company_data['유동부채(천원)']) / company_data['총자산(천원)']) / ((company_data['비유동부채(천원)'].shift(1) + company_data['유동부채(천원)'].shift(1)) / company_data['총자산(천원)'].shift(1))
C:\Users\Master\AppData\Local\Temp\ipykernel_17828\278330576.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['LVGI'] = ((company_data['비유동부채(천원)'] + company_data['유동부채(천원)']) / company_data['총자산(천원)']) / ((company_data['비유동부채(천원)'].shift(1) + company_data['유동부채(천원)'].shift(1)) / company_data['총자산(천원)'].shift(1))

In [24]:
# t년도와 t-1년도의 값을 비교하여 새로운 열을 만들거나 해당 열을 변경
# (당기 영업이익 - 당기 영업현금흐름) / 당기 총자산
# TATA
for company in df['Name'].unique():
    company_data = df[df['Name'] == company]
    company_data['TATA'] = (company_data['영업이익(천원)'] - company_data['영업활동으로인한현금흐름(천원)']) / company_data['총자산(천원)']
    df.loc[company_data.index, 'TATA'] = company_data['TATA']

C:\Users\Master\AppData\Local\Temp\ipykernel_17828\3241776078.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['TATA'] = (company_data['영업이익(천원)'] - company_data['영업활동으로인한현금흐름(천원)']) / company_data['총자산(천원)']
C:\Users\Master\AppData\Local\Temp\ipykernel_17828\3241776078.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  company_data['TATA'] = (company_data['영업이익(천원)'] - company_data['영업활동으로인한현금흐름(천원)']) / company_data['총자산(천원)']

생성된 피쳐들 Benish 데이터프레임으로 따로 생성
각 피쳐들 계산한 M_score 컬럼도 추가

In [25]:
Benish = pd.DataFrame(columns = ['Symbol', 'Name', '회계년', 'DSRI', 'GMI', 'AQI', 'SGI', 'DEPI', 'SGAI', 'LVGI', 'TATA'])
Benish['Symbol'] = df['Symbol']
Benish['Name'] = df['Name']
Benish['회계년'] = df['회계년']
Benish['DSRI'] = df['DSRI']
Benish['GMI'] = df['GMI']
Benish['AQI'] = df['AQI']
Benish['SGI'] = df['SGI']
Benish['DEPI'] = df['DEPI']
Benish['SGAI'] = df['SGAI']
Benish['LVGI'] = df['LVGI']
Benish['TATA'] = df['TATA']

In [13]:
Benish['M_score'] =  -4.84 + 0.92 * Benish['DSRI'] + 0.528 * Benish['GMI'] + 0.404 * Benish['AQI'] + 0.892 * Benish['SGI'] + 0.115 * Benish['DEPI'] - 0.172 * Benish['SGAI'] + 4.679 * Benish['TATA'] - 0.327 * Benish['LVGI']

In [27]:
#Benish.to_csv('코스닥_베니시.csv', index = False, encoding='utf-8-sig')

In [26]:
Benish

        Symbol    Name   회계년  DSRI  GMI  AQI  SGI  DEPI  SGAI  LVGI  TATA
0      A247540  에코프로비엠  2011   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
1      A247540  에코프로비엠  2012   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
2      A247540  에코프로비엠  2013   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
3      A247540  에코프로비엠  2014   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
4      A247540  에코프로비엠  2015   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
...        ...     ...   ...   ...  ...  ...  ...   ...   ...   ...   ...
27835  A900180      완리  2018   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
27836  A900180      완리  2019   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
27837  A900180      완리  2020   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
27838  A900180      완리  2021   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN
27839  A900180      완리  2022   NaN  NaN  NaN  NaN   NaN   NaN   NaN   NaN

[27840 rows x 11 columns]

In [13]:
Benish['M_score'].value_counts()

KeyError: 'M_score'

In [16]:
import numpy as np

# 'manipulate' 열을 NaN으로 초기화
Benish['manipulate'] = np.nan

# 조건에 따라 'manipulate' 열 채우기
Benish.loc[np.isnan(Benish['M_score']), 'manipulate'] = np.nan
Benish.loc[Benish['M_score'] < -2.22, 'manipulate'] = 0
Benish.loc[Benish['M_score'] >= -2.22, 'manipulate'] = 1

In [17]:
Benish['manipulate'] = np.nan
# 조건에 따라 'manipulate' 열 채우기
Benish.loc[np.isnan(Benish['M_score']), 'manipulate'] = np.nan
Benish.loc[Benish['M_score'] < -2.22, 'manipulate'] = 0
Benish.loc[Benish['M_score'] >= -2.22, 'manipulate'] = 1

# 결과를 새 CSV 파일로 저장
#Benish.to_csv('코스피_beniesh_M_score.csv', index=False, encoding='utf-8-sig')

In [18]:
Benish

,Symbol,Name,회계년,DSRI,GMI,AQI,SGI,DEPI,SGAI,LVGI,TATA,M_score,manipulate
0,A005930,삼성전자,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.046685,NaN,NaN
1,A005930,삼성전자,2012,0.894689,0.865279,0.978884,1.218797,0.010662,1.001059,0.941047,-0.049281,-2.786649,0.0
2,A005930,삼성전자,2013,0.920906,0.930428,0.929372,1.137188,0.011489,1.049976,0.909246,-0.046350,-2.805133,0.0
3,A005930,삼성전자,2014,1.096005,1.052893,1.148993,0.901673,0.012529,1.082266,0.904046,-0.051863,-2.730259,0.0
4,A005930,삼성전자,2015,1.047373,0.982603,0.854211,0.973073,0.013063,0.986019,0.963436,-0.056356,-2.891347,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9184,A950010,평산차업 KDR,2012,1.264381,1.358430,0.461661,0.766340,0.000000,1.146383,1.026867,-0.074683,-2.971837,0.0
9185,A950010,평산차업 KDR,2013,1.100433,0.789968,11.240922,1.126943,0.000000,0.921792,1.011008,-0.027439,1.518534,1.0
9186,A950010,평산차업 KDR,2014,0.141771,0.331720,1.195305,0.729570,0.000000,1.296470,1.170136,-0.029925,-4.146390,0.0
9187,A950070,중국고섬,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.033623,NaN,NaN
9188,A950070,중국고섬,2012,2.011561,0.397187,0.754792,0.871838,0.000000,1.831793,2.006525,0.003143,-2.653528,0.0

In [19]:
Benish['manipulate'].value_counts()

0.0    6321
1.0    1950
Name: manipulate, dtype: int64

In [ ]:
Benish.loc[Benish['Name'] == '현대건설', ]

In [ ]:
Benish.loc[Benish['Name'] == '삼성바이오로직스', ]

In [ ]:
Benish.loc[Benish['DSRI'] == np.inf]

,Symbol,Name,회계년,DSRI,GMI,AQI,SGI,DEPI,SGAI,LVGI,TATA,M_score,manipulate
98,A035420,NAVER,2022,inf,1.000000,9.537980e-01,1.205714,0.170332,1.044320,1.074606,-0.004387,inf,1.0
244,A033780,KT&G,2012,inf,0.997195,9.558280e-01,1.050726,0.030428,1.098040,1.092301,0.039483,inf,1.0
425,A042660,한화오션,2012,inf,2.333937,1.119938e+00,0.976929,0.000000,1.250023,1.012101,0.059570,inf,1.0
489,A326030,SK바이오팜,2017,inf,NaN,1.786056e+00,0.000000,0.084083,inf,2.180881,-0.005997,NaN,NaN
491,A326030,SK바이오팜,2019,inf,1.004169,5.460399e+00,112.722429,0.143510,0.012819,2.831037,0.014927,inf,1.0
2811,A011930,신성이엔지,2022,inf,0.995638,7.991802e-01,1.461186,0.024950,0.762452,1.125679,0.077957,inf,1.0
3134,A003520,영진약품,2018,inf,1.071081,9.304522e-01,0.955899,0.005089,1.011373,1.043277,-0.017651,inf,1.0
3500,A084010,대한제강,2022,inf,0.979966,1.242051e+00,1.054825,0.008955,1.044835,0.832007,0.116526,inf,1.0
3616,A004380,삼익THK,2018,inf,0.905082,9.355995e-01,0.762765,0.007412,1.268705,1.156764,0.012086,inf,1.0
4427,A008060,대덕,2019,inf,NaN,1.792502e+00,0.000000,0.002290,inf,1.002566,-0.152172,NaN,NaN
4430,A008060,대덕,2022,inf,0.608647,1.063161e+00,1.211560,0.018894,1.096914,1.081266,-0.065662,inf,1.0
4485,A074610,이엔플러스,2017,inf,1.412813,1.884929e+00,1.164696,0.023385,1.487573,2.028414,0.404575,inf,1.0
6096,A012170,아센디오,2014,inf,-18.136739,9.313420e-01,0.539106,0.469059,1.166422,1.201294,0.008639,inf,1.0
6194,A145210,다이나믹디자인,2016,inf,1.055341,9.591704e-01,0.896711,0.007713,1.157172,1.065677,-0.024434,inf,1.0
6322,A000230,일동홀딩스,2018,inf,1.039815,1.000842e+00,1.145587,0.025335,0.873019,1.036584,-0.023410,inf,1.0
6553,A244920,에이플러스에셋,2013,inf,1.000000,1.303147e+00,0.687295,0.420801,1.026166,1.326918,0.080466,inf,1.0
6558,A244920,에이플러스에셋,2018,inf,1.000000,9.196251e-01,1.183470,0.489569,1.013268,1.841601,-0.044164,inf,1.0
6606,A016090,대현,2018,inf,0.982797,9.273789e-01,1.009242,0.101194,0.992425,0.945895,0.003973,inf,1.0
7508,A069730,DSR제강,2018,inf,1.032937,1.104331e+00,1.043419,0.001312,0.730324,1.001583,-0.019729,inf,1.0
7517,A143210,핸즈코퍼레이션,2015,inf,0.486241,8.967434e-01,1.176808,0.006652,1.058600,0.959046,0.089152,inf,1.0
7580,A008420,문배철강,2018,inf,1.459337,1.002126e+00,1.021613,0.015437,0.855651,0.775550,-0.044815,inf,1.0
7971,A002420,세기상사,2012,inf,0.814216,3.200798e-01,1.012421,0.001061,1.070697,1.008268,-0.004083,inf,1.0
8467,A030790,비케이탑스,2016,inf,0.974614,6.861627e-01,0.837658,0.256521,1.115531,1.159455,-0.044378,inf,1.0
8554,A002250,알보젠코리아,2018,inf,1.019712,1.045168e+00,1.019337,0.113347,1.014729,0.499224,-0.008995,inf,1.0
8685,A004510,디와이홀딩스,2022,inf,1.043352,9.949428e-01,0.882270,NaN,1.665184,1.059135,0.085604,NaN,NaN
8738,A005560,JS전선,2017,inf,NaN,1.584944e-01,0.000000,0.042996,inf,0.474280,0.085806,NaN,NaN
8911,A014590,티엘씨레저,2022,inf,129.563790,9.326897e-01,139.347650,0.000630,0.007774,1.178668,-0.028083,inf,1.0
9158,A144620,코오롱머티리얼,2021,inf,NaN,1.180156e+00,0.000000,0.055769,inf,0.965873,0.043890,NaN,NaN
9178,A900050,중국원양자원,2012,inf,1.112903,3.961529e+07,0.916550,0.000090,1.253837,0.724566,0.023131,inf,1.0

In [ ]:
Benish.loc[Benish['Name'] == '한화오션', ]

,Symbol,Name,회계년,DSRI,GMI,AQI,SGI,DEPI,SGAI,LVGI,TATA,M_score,manipulate
424,A042660,한화오션,2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.058372,NaN,NaN
425,A042660,한화오션,2012,inf,2.333937,1.119938,0.976929,0.000000,1.250023,1.012101,0.059570,inf,1.0
426,A042660,한화오션,2013,1.279515,-31.633226,0.632822,1.076885,0.000000,1.264131,1.099443,0.011199,-19.673497,0.0
427,A042660,한화오션,2014,0.647170,-0.182553,0.865617,1.066969,0.002486,0.659530,1.073048,-0.000273,-3.504862,0.0
428,A042660,한화오션,2015,1.530822,-0.081909,1.448521,0.992421,0.001108,0.795738,1.092015,-0.067874,-2.815864,0.0
429,A042660,한화오션,2016,0.795036,2.074806,0.908558,0.830066,0.001235,1.976327,0.988637,-0.066369,-2.879204,0.0
430,A042660,한화오션,2017,1.522841,-0.353535,0.558171,0.866029,0.001031,1.040031,0.772547,0.153135,-2.342523,0.0
431,A042660,한화오션,2018,1.892479,1.784545,0.904164,0.868721,0.001289,-0.387687,0.917509,0.025145,-1.132040,1.0
432,A042660,한화오션,2019,0.603255,1.389186,1.007254,0.866696,0.000670,-0.744212,0.984080,-0.199481,-3.498578,0.0
433,A042660,한화오션,2020,2.015598,0.996189,1.075808,0.841056,0.001804,1.636351,0.937219,0.059289,-1.585117,1.0
434,A042660,한화오션,2021,0.690179,-0.163322,0.934129,0.638190,0.001197,1.341127,1.265743,-0.210900,-4.975852,0.0
435,A042660,한화오션,2022,1.165072,1.244298,0.808583,1.083263,0.000913,1.186175,1.186873,-0.044798,-2.619840,0.0

In [ ]:
df = Benish.drop(columns = ['Symbol', 'Name', '회계년', 'manipulate'])
df

,DSRI,GMI,AQI,SGI,DEPI,SGAI,LVGI,TATA,M_score
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.046685,NaN
1,0.894689,0.865279,0.978884,1.218797,0.010662,1.001059,0.941047,-0.049281,-2.786649
2,0.920906,0.930428,0.929372,1.137188,0.011489,1.049976,0.909246,-0.046350,-2.805133
3,1.096005,1.052893,1.148993,0.901673,0.012529,1.082266,0.904046,-0.051863,-2.730259
4,1.047373,0.982603,0.854211,0.973073,0.013063,0.986019,0.963436,-0.056356,-2.891347
...,...,...,...,...,...,...,...,...,...
9184,1.264381,1.358430,0.461661,0.766340,0.000000,1.146383,1.026867,-0.074683,-2.971837
9185,1.100433,0.789968,11.240922,1.126943,0.000000,0.921792,1.011008,-0.027439,1.518534
9186,0.141771,0.331720,1.195305,0.729570,0.000000,1.296470,1.170136,-0.029925,-4.146390
9187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.033623,NaN
9188,2.011561,0.397187,0.754792,0.871838,0.000000,1.831793,2.006525,0.003143,-2.653528

In [ ]:
df = df.dropna(subset=['DSRI', 'GMI', 'DEPI'])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8271 entries, 1 to 9188
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DSRI     8271 non-null   float64
 1   GMI      8271 non-null   float64
 2   AQI      8271 non-null   float64
 3   SGI      8271 non-null   float64
 4   DEPI     8271 non-null   float64
 5   SGAI     8271 non-null   float64
 6   LVGI     8271 non-null   float64
 7   TATA     8271 non-null   float64
 8   M_score  8271 non-null   float64
dtypes: float64(9)
memory usage: 646.2 KB

In [ ]:
import numpy as np
df.replace([np.inf, -np.inf], np.nan, inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8271 entries, 1 to 9188
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   DSRI     8247 non-null   float64
 1   GMI      8271 non-null   float64
 2   AQI      8271 non-null   float64
 3   SGI      8271 non-null   float64
 4   DEPI     8271 non-null   float64
 5   SGAI     8271 non-null   float64
 6   LVGI     8271 non-null   float64
 7   TATA     8271 non-null   float64
 8   M_score  8247 non-null   float64
dtypes: float64(9)
memory usage: 646.2 KB

C:\Users\Master\AppData\Local\Temp\ipykernel_12904\2131473679.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.replace([np.inf, -np.inf], np.nan, inplace=True)