In [24]:
import pandas as pd
from scipy import stats

df = pd.read_csv('../data/dataset/코스피_최종.csv')
df.head(2)

,Symbol,Name,결산월,회계년,주기,분식기업,매출총이익률(%),영업이익률(%),당기순이익률(%),자본금영업이익률(%),...,영업현금흐름/투자현금흐름(%),DSRI,GMI,AQI,SGI,DEPI,SGAI,LVGI,TATA,벤포드
0,A095570,AJ네트웍스,12,2015,Annual,0.0,100.0,7.03,2.75,183.57,...,1.43,1.03,1.0,0.81,1.04,0.18,1.01,0.96,0.10,0
1,A095570,AJ네트웍스,12,2016,Annual,0.0,100.0,4.93,1.36,132.12,...,2.19,1.13,1.0,1.28,1.19,0.17,1.02,1.03,0.12,0

In [32]:
df.describe()

,결산월,회계년,분식기업,매출총이익률(%),영업이익률(%),당기순이익률(%),자본금영업이익률(%),영업수익/영업비용(%),ROE(세전계속사업이익)(%),자본금세전계속사업이익률(%),...,영업현금흐름/투자현금흐름(%),DSRI,GMI,AQI,SGI,DEPI,SGAI,LVGI,TATA,벤포드
count,7029.0,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000,...,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000,7029.000000
mean,12.0,2017.365059,0.020202,22.214233,3.535648,1.650148,269.718994,104.869165,3.727847,271.599319,...,-1.316331,1.042338,1.005163,1.123905,1.092818,0.037818,1.031271,1.011428,-0.010797,0.094466
std,0.0,3.074980,0.140701,20.843268,12.014931,22.995030,757.050435,11.130006,30.115148,882.772068,...,11.988252,0.553396,1.150366,0.727827,0.432729,0.089672,0.273244,0.254851,0.063086,0.292496
min,12.0,2012.000000,0.000000,-169.576000,-144.225200,-252.965800,-2763.250000,19.020000,-358.737600,-7451.332600,...,-131.897000,0.000000,-9.932600,0.040000,0.000000,0.000000,-1.660800,0.110000,-0.715000,0.000000
25%,12.0,2015.000000,0.000000,10.180000,1.390000,0.220000,15.110000,101.410000,1.080000,6.000000,...,-1.790000,0.870000,0.900000,0.900000,0.960000,0.000000,0.930000,0.930000,-0.040000,0.000000
50%,12.0,2017.000000,0.000000,16.360000,4.120000,2.960000,81.460000,104.300000,6.770000,73.680000,...,-0.850000,0.980000,1.000000,1.000000,1.040000,0.010000,1.010000,0.990000,-0.010000,0.000000
75%,12.0,2020.000000,0.000000,27.210000,7.500000,6.390000,247.480000,108.110000,12.910000,256.230000,...,-0.060000,1.100000,1.100000,1.130000,1.140000,0.030000,1.090000,1.050000,0.020000,0.000000
max,12.0,2022.000000,1.000000,100.000000,82.100000,212.591000,9493.648400,241.332400,292.584000,11012.006600,...,118.472600,7.365000,12.030600,9.648800,6.203600,0.980000,4.128000,4.003800,0.460000,1.000000

In [25]:
# 타겟 변수에 따라 두 그룹으로 나눔
group0 = df[df['분식기업'] == 0]
group1 = df[df['분식기업'] == 1]

In [26]:
df.columns[6:]

Index(['매출총이익률(%)', '영업이익률(%)', '당기순이익률(%)', '자본금영업이익률(%)', '영업수익/영업비용(%)',
       'ROE(세전계속사업이익)(%)', '자본금세전계속사업이익률(%)', '자본금지배주주순이익률(%)',
       '매출액증가율(전년동기)(%)', '영업이익증가율(전년동기)(%)', '당기순이익증가율(전년동기)(%)',
       '총자본증가율(전년동기)(%)', '유형자산증가율(전년동기)(%)', '부채비율(%)', '유동비율(%)', '당좌비율(%)',
       '현금및현금성자산구성비율(%)', '유형자산구성비율(%)', '무형자산구성비율(%)', '판관비율(%)', '타인자본비율(%)',
       '총자산회전율(회)', '매출채권회전율(회)', '재고자산회전율(회)', '총부채회전율(회)', '총자본회전율(회)',
       '자본금회전율(회)', '고정자산회전율(회)', '현금흐름/총부채(%)', '현금흐름/영업수익(%)', '현금흐름/총자본(%)',
       '영업현금흐름/투자현금흐름(%)', 'DSRI', 'GMI', 'AQI', 'SGI', 'DEPI', 'SGAI', 'LVGI',
       'TATA', '벤포드'],
      dtype='object')

## T-Test 진행

In [27]:
# 결과 저장할 리스트
results = []

# 독립 변수들에 대해 t-test 진행
for col in df.columns[6:]:
    stat, p_value = stats.ttest_ind(group1[col], group0[col], nan_policy='omit')  # t-test 수행
    results.append({'Variable': col, 't-statistic': stat, 'p-value': p_value})

# 결과를 데이터프레임으로 변환
t_test_results = pd.DataFrame(results)

In [28]:
# p-value가 유의미한 변수만 필터링 (예: 0.05 이하)
t_test_feature = t_test_results[t_test_results['p-value'] < 0.05]
t_test_feature

            Variable  t-statistic       p-value
3        자본금영업이익률(%)    -2.586413  9.717993e-03
5   ROE(세전계속사업이익)(%)    -2.119112  3.411595e-02
7     자본금지배주주순이익률(%)    -2.138930  3.247569e-02
9   영업이익증가율(전년동기)(%)     3.362502  7.765215e-04
11   총자본증가율(전년동기)(%)    -3.280096  1.042771e-03
13           부채비율(%)     5.311723  1.119257e-07
14           유동비율(%)    -2.221174  2.637095e-02
15           당좌비율(%)    -2.157259  3.101930e-02
16   현금및현금성자산구성비율(%)    -2.381631  1.726262e-02
19           판관비율(%)    -2.297551  2.161663e-02
20         타인자본비율(%)     6.185940  6.519747e-10
21         총자산회전율(회)    -3.014450  2.583644e-03
22        매출채권회전율(회)    -2.154482  3.123631e-02
24         총부채회전율(회)    -4.695856  2.705317e-06
26         자본금회전율(회)    -2.906653  3.664605e-03
27        고정자산회전율(회)     2.840387  4.518836e-03
28       현금흐름/총부채(%)    -2.474881  1.335149e-02
30       현금흐름/총자본(%)    -3.344856  8.275656e-04
37              SGAI     2.131934  3.304686e-02

## 비모수 검정 (Mann-Whitney U test)

In [29]:
from scipy.stats import mannwhitneyu

# 결과 저장할 리스트
results2 = []

# 각 컬럼에 대해 Mann-Whitney U 테스트 수행
for column in df.columns[6:]:
    stat, p_value = mannwhitneyu(group1[column], group0[column])
    results2.append({'Variable': column, 't-statistic': stat, 'p-value': p_value})

# 결과를 데이터프레임으로 변환
whitney_test_results = pd.DataFrame(results2)

In [30]:
# p-value가 유의미한 변수만 필터링 (예: 0.05 이하)

whitney_test_feature = whitney_test_results[whitney_test_results['p-value'] < 0.05]
whitney_test_feature

           Variable  t-statistic       p-value
2         당기순이익률(%)     440901.0  4.458731e-02
3       자본금영업이익률(%)     420084.0  3.999118e-03
6   자본금세전계속사업이익률(%)     416465.0  2.450173e-03
7    자본금지배주주순이익률(%)     407124.5  6.269923e-04
11  총자본증가율(전년동기)(%)     405166.5  4.627099e-04
13          부채비율(%)     611319.0  3.200255e-07
14          유동비율(%)     423498.5  6.227076e-03
20        타인자본비율(%)     622390.0  2.492620e-08
21        총자산회전율(회)     431139.0  1.567306e-02
22       매출채권회전율(회)     385411.0  1.512751e-05
23       재고자산회전율(회)     380629.0  5.993475e-06
24        총부채회전율(회)     352192.5  1.099208e-08
26        자본금회전율(회)     405344.0  4.757557e-04
28      현금흐름/총부채(%)     384921.0  1.378287e-05
29     현금흐름/영업수익(%)     423920.0  6.568393e-03
30      현금흐름/총자본(%)     428153.5  1.105045e-02

In [31]:
t_test_variable = t_test_feature[['Variable']]
whitney_test_variable = whitney_test_feature[['Variable']]

# 두 컬럼을 이어붙여 C라는 새로운 데이터프레임으로 생성
compare_df = pd.concat([t_test_variable, whitney_test_variable], axis=1)
compare_df

            Variable         Variable
3        자본금영업이익률(%)      자본금영업이익률(%)
5   ROE(세전계속사업이익)(%)              NaN
7     자본금지배주주순이익률(%)   자본금지배주주순이익률(%)
9   영업이익증가율(전년동기)(%)              NaN
11   총자본증가율(전년동기)(%)  총자본증가율(전년동기)(%)
13           부채비율(%)          부채비율(%)
14           유동비율(%)          유동비율(%)
15           당좌비율(%)              NaN
16   현금및현금성자산구성비율(%)              NaN
19           판관비율(%)              NaN
20         타인자본비율(%)        타인자본비율(%)
21         총자산회전율(회)        총자산회전율(회)
22        매출채권회전율(회)       매출채권회전율(회)
24         총부채회전율(회)        총부채회전율(회)
26         자본금회전율(회)        자본금회전율(회)
27        고정자산회전율(회)              NaN
28       현금흐름/총부채(%)      현금흐름/총부채(%)
30       현금흐름/총자본(%)      현금흐름/총자본(%)
37              SGAI              NaN
2                NaN        당기순이익률(%)
6                NaN  자본금세전계속사업이익률(%)
23               NaN       재고자산회전율(회)
29               NaN     현금흐름/영업수익(%)